-- =====================================================================
-- LOYALTY PLATFORM — Script DDL (Oracle 12c+)
-- Sprint 3 — Domain Driven Design using Java
-- Equipe HalfTech — Turma 1TDSPW
-- =====================================================================
-- Ordem: DROP (filhas primeiro) → CREATE (pais primeiro)
-- Se as tabelas ainda não existirem, os DROP acusam erro e o script segue.
-- =====================================================================

DROP TABLE TB_USUARIO_MISSAO   CASCADE CONSTRAINTS;
DROP TABLE TB_INTERACAO        CASCADE CONSTRAINTS;
DROP TABLE TB_RANKING          CASCADE CONSTRAINTS;
DROP TABLE TB_SEQUENCIA        CASCADE CONSTRAINTS;
DROP TABLE TB_EMPRESA_USUARIO  CASCADE CONSTRAINTS;
DROP TABLE TB_MISSAO           CASCADE CONSTRAINTS;
DROP TABLE TB_CAMPANHA         CASCADE CONSTRAINTS;
DROP TABLE TB_USUARIO          CASCADE CONSTRAINTS;
DROP TABLE TB_EMPRESA          CASCADE CONSTRAINTS;
DROP TABLE TB_NIVEL            CASCADE CONSTRAINTS;


-- =====================================================================
-- TB_NIVEL — faixas de classificação por pontuação
-- =====================================================================
CREATE TABLE TB_NIVEL
    (
     id_nivel             INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
     nome_nivel           VARCHAR2(50)  NOT NULL,
     pontos_minimos_nivel INTEGER       NOT NULL,
     pontos_maximos_nivel INTEGER       NOT NULL,

     CONSTRAINT TB_NIVEL_PK        PRIMARY KEY (id_nivel),
     CONSTRAINT TB_NIVEL_FAIXA_CK  CHECK (pontos_minimos_nivel >= 0
                                          AND pontos_maximos_nivel > pontos_minimos_nivel)
    );


-- =====================================================================
-- TB_EMPRESA — empresas clientes que contratam a plataforma
-- =====================================================================
CREATE TABLE TB_EMPRESA
    (
     id_empresa            INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
     nome_empresa          VARCHAR2(100) NOT NULL,
     cnpj_empresa          CHAR(14)      NOT NULL,
     email_empresa         VARCHAR2(100) NOT NULL,
     telefone_empresa      VARCHAR2(20),
     data_cadastro_empresa DATE DEFAULT SYSDATE NOT NULL,
     status_empresa        VARCHAR2(20) DEFAULT 'ATIVA' NOT NULL,

     CONSTRAINT TB_EMPRESA_PK         PRIMARY KEY (id_empresa),
     CONSTRAINT TB_EMPRESA_CNPJ_UK    UNIQUE (cnpj_empresa),
     CONSTRAINT TB_EMPRESA_EMAIL_UK   UNIQUE (email_empresa),
     CONSTRAINT TB_EMPRESA_STATUS_CK  CHECK (status_empresa IN ('ATIVA', 'INATIVA'))
    );


-- =====================================================================
-- TB_USUARIO — usuários finais da plataforma
-- A identidade é única; pontuação e nível são POR VÍNCULO (TB_EMPRESA_USUARIO)
-- =====================================================================
CREATE TABLE TB_USUARIO
    (
     id_usuario    INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
     nome_usuario  VARCHAR2(100) NOT NULL,
     email_usuario VARCHAR2(100) NOT NULL,
     senha_usuario VARCHAR2(100) NOT NULL,
     data_cadastro DATE DEFAULT SYSDATE NOT NULL,

     CONSTRAINT TB_USUARIO_PK       PRIMARY KEY (id_usuario),
     CONSTRAINT TB_USUARIO_EMAIL_UK UNIQUE (email_usuario)
    );


-- =====================================================================
-- TB_EMPRESA_USUARIO — vínculo usuário-empresa
-- Aqui moram a pontuação acumulada e o nível, ambos por empresa
-- =====================================================================
CREATE TABLE TB_EMPRESA_USUARIO
    (
     TB_EMPRESA_id_empresa INTEGER NOT NULL,
     TB_USUARIO_id_usuario INTEGER NOT NULL,
     TB_NIVEL_id_nivel     INTEGER NOT NULL,
     pontuacao_acumulada   INTEGER DEFAULT 0 NOT NULL,
     data_associacao       DATE DEFAULT SYSDATE NOT NULL,

     CONSTRAINT TB_EMPRESA_USUARIO_PK PRIMARY KEY (TB_EMPRESA_id_empresa, TB_USUARIO_id_usuario),
     CONSTRAINT TB_EMPUSU_EMPRESA_FK  FOREIGN KEY (TB_EMPRESA_id_empresa) REFERENCES TB_EMPRESA (id_empresa),
     CONSTRAINT TB_EMPUSU_USUARIO_FK  FOREIGN KEY (TB_USUARIO_id_usuario) REFERENCES TB_USUARIO (id_usuario),
     CONSTRAINT TB_EMPUSU_NIVEL_FK    FOREIGN KEY (TB_NIVEL_id_nivel)     REFERENCES TB_NIVEL (id_nivel),
     CONSTRAINT TB_EMPUSU_PONTOS_CK   CHECK (pontuacao_acumulada >= 0)
    );


-- =====================================================================
-- TB_CAMPANHA — campanhas de gamificação criadas pela empresa cliente
-- =====================================================================
CREATE TABLE TB_CAMPANHA
    (
     id_campanha           INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
     nome_campanha         VARCHAR2(100) NOT NULL,
     descricao_campanha    VARCHAR2(500),
     data_inicio_campanha  DATE          NOT NULL,
     data_fim_campanha     DATE,
     status_campanha       VARCHAR2(20) DEFAULT 'INATIVA' NOT NULL,
     TB_EMPRESA_id_empresa INTEGER       NOT NULL,

     CONSTRAINT TB_CAMPANHA_PK        PRIMARY KEY (id_campanha),
     CONSTRAINT TB_CAMPANHA_EMPRESA_FK FOREIGN KEY (TB_EMPRESA_id_empresa) REFERENCES TB_EMPRESA (id_empresa),
     CONSTRAINT TB_CAMPANHA_STATUS_CK CHECK (status_campanha IN ('ATIVA', 'INATIVA', 'ENCERRADA')),
     CONSTRAINT TB_CAMPANHA_DATAS_CK  CHECK (data_fim_campanha IS NULL
                                             OR data_fim_campanha >= data_inicio_campanha)
    );


-- =====================================================================
-- TB_MISSAO — missões associadas a uma campanha
-- =====================================================================
CREATE TABLE TB_MISSAO
    (
     id_missao                INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
     nome_missao              VARCHAR2(100) NOT NULL,
     descricao_missao         VARCHAR2(400),
     meta_missao              INTEGER       NOT NULL,
     pontos_recompensa_missao INTEGER       NOT NULL,
     status_missao            VARCHAR2(20) DEFAULT 'ATIVA' NOT NULL,
     TB_CAMPANHA_id_campanha  INTEGER       NOT NULL,

     CONSTRAINT TB_MISSAO_PK         PRIMARY KEY (id_missao),
     CONSTRAINT TB_MISSAO_CAMPANHA_FK FOREIGN KEY (TB_CAMPANHA_id_campanha) REFERENCES TB_CAMPANHA (id_campanha),
     CONSTRAINT TB_MISSAO_STATUS_CK  CHECK (status_missao IN ('ATIVA', 'INATIVA', 'EXCLUIDA')),
     CONSTRAINT TB_MISSAO_META_CK    CHECK (meta_missao > 0),
     CONSTRAINT TB_MISSAO_PONTOS_CK  CHECK (pontos_recompensa_missao > 0)
    );


-- =====================================================================
-- TB_USUARIO_MISSAO — progresso de cada usuário em cada missão
-- =====================================================================
CREATE TABLE TB_USUARIO_MISSAO
    (
     TB_USUARIO_id_usuario  INTEGER NOT NULL,
     TB_MISSAO_id_missao    INTEGER NOT NULL,
     progresso_atual_missao INTEGER DEFAULT 0 NOT NULL,
     data_inicio_missao     DATE DEFAULT SYSDATE NOT NULL,
     data_conclusao         DATE,
     data_resgate           DATE,

     CONSTRAINT TB_USUARIO_MISSAO_PK   PRIMARY KEY (TB_USUARIO_id_usuario, TB_MISSAO_id_missao),
     CONSTRAINT TB_USRMISSAO_USUARIO_FK FOREIGN KEY (TB_USUARIO_id_usuario) REFERENCES TB_USUARIO (id_usuario),
     CONSTRAINT TB_USRMISSAO_MISSAO_FK  FOREIGN KEY (TB_MISSAO_id_missao)   REFERENCES TB_MISSAO (id_missao),
     CONSTRAINT TB_USRMISSAO_PROG_CK    CHECK (progresso_atual_missao >= 0)
    );


-- =====================================================================
-- TB_INTERACAO — registro das interações do usuário
-- =====================================================================
CREATE TABLE TB_INTERACAO
    (
     TB_USUARIO_id_usuario INTEGER      NOT NULL,
     TB_EMPRESA_id_empresa INTEGER      NOT NULL,
     data_interacao        DATE         NOT NULL,
     tipo_interacao        VARCHAR2(50) NOT NULL,

     CONSTRAINT TB_INTERACAO_PK         PRIMARY KEY (TB_USUARIO_id_usuario, TB_EMPRESA_id_empresa, data_interacao),
     CONSTRAINT TB_INTERACAO_USUARIO_FK FOREIGN KEY (TB_USUARIO_id_usuario) REFERENCES TB_USUARIO (id_usuario),
     CONSTRAINT TB_INTERACAO_EMPRESA_FK FOREIGN KEY (TB_EMPRESA_id_empresa) REFERENCES TB_EMPRESA (id_empresa)
    );


-- =====================================================================
-- TB_RANKING — classificação dos usuários POR EMPRESA
-- =====================================================================
CREATE TABLE TB_RANKING
    (
     TB_USUARIO_id_usuario    INTEGER NOT NULL,
     TB_EMPRESA_id_empresa    INTEGER NOT NULL,
     posicao_ranking          INTEGER NOT NULL,
     pontuacao_ranking        INTEGER DEFAULT 0 NOT NULL,
     data_atualizacao_ranking DATE DEFAULT SYSDATE NOT NULL,

     CONSTRAINT TB_RANKING_PK         PRIMARY KEY (TB_USUARIO_id_usuario, TB_EMPRESA_id_empresa),
     CONSTRAINT TB_RANKING_USUARIO_FK FOREIGN KEY (TB_USUARIO_id_usuario) REFERENCES TB_USUARIO (id_usuario),
     CONSTRAINT TB_RANKING_EMPRESA_FK FOREIGN KEY (TB_EMPRESA_id_empresa) REFERENCES TB_EMPRESA (id_empresa),
     CONSTRAINT TB_RANKING_POSICAO_CK CHECK (posicao_ranking >= 1),
     CONSTRAINT TB_RANKING_PONTOS_CK  CHECK (pontuacao_ranking >= 0)
    );


-- =====================================================================
-- TB_SEQUENCIA — dias consecutivos de interação, POR EMPRESA
-- =====================================================================
CREATE TABLE TB_SEQUENCIA
    (
     TB_USUARIO_id_usuario INTEGER   NOT NULL,
     TB_EMPRESA_id_empresa INTEGER   NOT NULL,
     dias_consecutivos     INTEGER DEFAULT 0 NOT NULL,
     status_sequencia      VARCHAR2(20) DEFAULT 'ATIVA' NOT NULL,
     data_inicio_sequencia DATE DEFAULT SYSDATE NOT NULL,
     ultimo_acesso         TIMESTAMP NOT NULL,
     data_desativacao      DATE,

     CONSTRAINT TB_SEQUENCIA_PK         PRIMARY KEY (TB_USUARIO_id_usuario, TB_EMPRESA_id_empresa),
     CONSTRAINT TB_SEQUENCIA_USUARIO_FK FOREIGN KEY (TB_USUARIO_id_usuario) REFERENCES TB_USUARIO (id_usuario),
     CONSTRAINT TB_SEQUENCIA_EMPRESA_FK FOREIGN KEY (TB_EMPRESA_id_empresa) REFERENCES TB_EMPRESA (id_empresa),
     CONSTRAINT TB_SEQUENCIA_STATUS_CK  CHECK (status_sequencia IN ('ATIVA', 'SUSPENSA', 'ZERADA')),
     CONSTRAINT TB_SEQUENCIA_DIAS_CK    CHECK (dias_consecutivos >= 0)
    );

COMMIT;
